package college;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 * @author Tanay
 */
public class CreateAccount4 extends javax.swing.JFrame {

    String loginAs, UserID;

    public CreateAccount4(String _UserID, String _loginAs) {
        initComponents();
        this.UserID = _UserID;
        this.loginAs = _loginAs;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setMaximumSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setMinimumSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("HP Simplified Light", 0, 50)); // NOI18N
        jLabel3.setText("Create account - 3");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(120, 20, 380, 70);

        jLabel9.setFont(new java.awt.Font("HP Simplified Light", 0, 24)); // NOI18N
        jLabel9.setText("Set  username");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(570, 40, 140, 40);

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 25)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 153, 0));
        jLabel11.setText("----------------");
        jLabel11.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel11);
        jLabel11.setBounds(960, 60, 170, 70);

        jLabel20.setFont(new java.awt.Font("HP Simplified Light", 0, 24)); // NOI18N
        jLabel20.setText("Personal  details");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(760, 40, 160, 40);

        jLabel5.setFont(new java.awt.Font("HP Simplified Light", 0, 24)); // NOI18N
        jLabel5.setText("Security details");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(970, 40, 160, 40);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel21.setText("Answer the security questions.");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(280, 220, 300, 30);

        jLabel2.setFont(new java.awt.Font("HP Simplified Light", 0, 24)); // NOI18N
        jLabel2.setText("Q2.    What  is  your  birth  month  ?");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(360, 410, 410, 60);

        jTextField1.setBackground(new java.awt.Color(221, 221, 221));
        jTextField1.setFont(new java.awt.Font("HP Simplified Light", 0, 18)); // NOI18N
        jTextField1.setBorder(null);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(360, 350, 400, 40);

        jTextField2.setBackground(new java.awt.Color(221, 221, 221));
        jTextField2.setFont(new java.awt.Font("HP Simplified Light", 0, 18)); // NOI18N
        jTextField2.setBorder(null);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(360, 470, 400, 40);

        jTextField3.setBackground(new java.awt.Color(221, 221, 221));
        jTextField3.setFont(new java.awt.Font("HP Simplified Light", 0, 18)); // NOI18N
        jTextField3.setBorder(null);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(360, 600, 410, 40);

        jLabel4.setFont(new java.awt.Font("HP Simplified Light", 0, 24)); // NOI18N
        jLabel4.setText("Q3.    Which  is  your  favourite  food  dish  ?");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(360, 540, 430, 60);

        jLabel6.setFont(new java.awt.Font("HP Simplified Light", 0, 24)); // NOI18N
        jLabel6.setText("Q1.    In  which  city  you  were  born  ?");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(360, 290, 380, 60);

        jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel16);
        jLabel16.setBounds(280, 250, 550, 450);

        jButton1.setBackground(new java.awt.Color(221, 221, 221));
        jButton1.setFont(new java.awt.Font("HP Simplified Light", 1, 24)); // NOI18N
        jButton1.setText("Confirm & Create account");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(410, 810, 340, 80);

        jLabel7.setFont(new java.awt.Font("Microsoft JhengHei", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 0, 0));
        jLabel7.setText("* All fields are case sensitive");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(610, 250, 230, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Login.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(1920, 1080));
        jLabel1.setMinimumSize(new java.awt.Dimension(1920, 1080));
        jLabel1.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1920, 1080);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1920, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String Secure1 = jTextField1.getText();
        String Secure2 = jTextField2.getText();
        String Secure3 = jTextField3.getText(); 
        boolean GoAhead =true;
        if(Secure1.equals("")||Secure2.equals("")||Secure3.equals(""))
        {JOptionPane.showMessageDialog(null,
                    "Please answer all the questions");
                    GoAhead=false;
        }
if(GoAhead==true)
{
        try {

            //setup connection with database
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/college", "root", "TANay@99");

            String query = "update " + loginAs + " set Secure1=?,Secure2=?,Secure3=? where UserID=?";
            PreparedStatement preparedStmt = con.prepareStatement(query);

            preparedStmt.setString(1, Secure1);
            preparedStmt.setString(2, Secure2);
            preparedStmt.setString(3, Secure3);
            preparedStmt.setString(4, UserID);

            int rowAffected = preparedStmt.executeUpdate();
            JOptionPane.showMessageDialog(null,
                    "Account creation completed !.\nWith username as :- " + UserID+"\nCurrently your account is under review.");

            Login l= new Login();
            l.setVisible(true);
            this.dispose();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,
                    "Error !!!");
        }
}
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
