/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package college;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Tanay
 */
public class DashboardStudent extends javax.swing.JFrame {

    /**
     * Creates new form DashboardTeacher
     */
    String UserID,loginAs,year,prn,message="",_title="";
    public DashboardStudent(String _UserID,String _loginAs) {
        this.UserID = _UserID;
        this.loginAs=_loginAs;
        initComponents();
        String Account;
        if(loginAs.equals(" loginstudent "))
        {
            Account="Student";
        }
        else
        {
            Account="Teacher";
        }
   
        this.getDetails();  //noticeboard
        
        
         try
        {
             //setup connection with database
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/college","Student","Student@99");
            
            PreparedStatement stmt=con.prepareStatement
            ("select * from "+Account+" where UserID = ?");
            stmt.setString(1, UserID);
           
            ResultSet rs=stmt.executeQuery();
            while(rs.next())   
            {
            jLabel19.setText(rs.getString(2));  
            prn=rs.getString(2);
            jLabel10.setText(rs.getString(7)); 
            year=rs.getString(7);
            jLabel11.setText(rs.getString(9));  
            jLabel12.setText(rs.getString(3));  
            jLabel15.setText(rs.getString(1));  
            jLabel13.setText(rs.getString(12));  
            jLabel26.setText(rs.getString(8));  
            jLabel23.setText(rs.getString(10));
            if(rs.getString(11).equals("Male"))
            {
                 _title="Mr.";
            }
            else
            {
                 _title="Ms.";
            }
            jLabel9.setText(_title+" "+rs.getString(4)+"  "+rs.getString(6)+"  "+rs.getString(5));
            }
            
                      
        }
         catch (Exception e)
        {
            JOptionPane.showMessageDialog(null,
                "Unable to connect to database.");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        textArea1 = new java.awt.TextArea();
        jLabel24 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashboard");
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(null);

        jPanel1.setMaximumSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setMinimumSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setLayout(null);

        jLabel4.setFont(new java.awt.Font("HP Simplified Light", 0, 36)); // NOI18N
        jLabel4.setText("Admission ID :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(1960, -140, 210, 50);

        jLabel8.setFont(new java.awt.Font("HP Simplified Light", 0, 48)); // NOI18N
        jLabel8.setText("Hello,");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(190, 30, 120, 60);

        jLabel9.setFont(new java.awt.Font("HP Simplified Light", 0, 75)); // NOI18N
        jLabel9.setText("Tanay Dharmendra Patel");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(190, 90, 890, 110);

        jLabel10.setFont(new java.awt.Font("HP Simplified Light", 0, 36)); // NOI18N
        jLabel10.setText("Third year (TE.)");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(1550, 280, 300, 60);

        jLabel11.setFont(new java.awt.Font("HP Simplified Light", 0, 36)); // NOI18N
        jLabel11.setText("02");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(1560, 420, 100, 60);

        jLabel12.setFont(new java.awt.Font("HP Simplified Light", 0, 36)); // NOI18N
        jLabel12.setText("307165");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(1560, 490, 120, 50);

        jLabel13.setFont(new java.awt.Font("HP Simplified Light", 0, 36)); // NOI18N
        jLabel13.setText("1999-05-28");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(1560, 550, 200, 60);

        jLabel14.setFont(new java.awt.Font("HP Simplified Light", 0, 36)); // NOI18N
        jLabel14.setText("1234/ABCD");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(2180, -150, 230, 70);

        jLabel15.setFont(new java.awt.Font("HP Simplified Light", 0, 36)); // NOI18N
        jLabel15.setText("patel");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(1550, 210, 100, 50);

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("HP Simplified Light", 3, 36)); // NOI18N
        jButton1.setText("My Result");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(1450, 750, 270, 90);

        jLabel19.setFont(new java.awt.Font("HP Simplified Light", 0, 36)); // NOI18N
        jLabel19.setText("abcd/1234/xyzw");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(1550, 140, 270, 60);

        jLabel20.setFont(new java.awt.Font("HP Simplified Light", 0, 36)); // NOI18N
        jLabel20.setText("My details :");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(1320, 90, 170, 40);

        jLabel21.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tanay\\Downloads\\logout.png")); // NOI18N
        jLabel21.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel21MousePressed(evt);
            }
        });
        jPanel1.add(jLabel21);
        jLabel21.setBounds(30, 20, 60, 60);

        jLabel22.setText("Logout");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(50, 70, 48, 16);

        jLabel23.setFont(new java.awt.Font("HP Simplified Light", 0, 36)); // NOI18N
        jLabel23.setText("9403130058");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(1560, 630, 230, 40);

        textArea1.setBackground(new java.awt.Color(214, 224, 235));
        textArea1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        textArea1.setEditable(false);
        textArea1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        textArea1.setRows(1);
        jPanel1.add(textArea1);
        textArea1.setBounds(200, 290, 880, 450);

        jLabel24.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        jLabel24.setText("Noticeboard :");
        jPanel1.add(jLabel24);
        jLabel24.setBounds(200, 230, 300, 70);

        jLabel2.setFont(new java.awt.Font("HP Simplified Light", 0, 36)); // NOI18N
        jLabel2.setText("Username    :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(1340, 220, 220, 40);

        jLabel3.setFont(new java.awt.Font("HP Simplified Light", 0, 36)); // NOI18N
        jLabel3.setText("PRN               : ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(1340, 150, 230, 40);

        jLabel5.setFont(new java.awt.Font("HP Simplified Light", 0, 36)); // NOI18N
        jLabel5.setText("Year               :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(1340, 290, 220, 40);

        jLabel6.setFont(new java.awt.Font("HP Simplified Light", 0, 36)); // NOI18N
        jLabel6.setText("Batch             :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(1340, 360, 220, 40);

        jLabel7.setFont(new java.awt.Font("HP Simplified Light", 0, 36)); // NOI18N
        jLabel7.setText("Division         :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(1340, 430, 220, 40);

        jLabel16.setFont(new java.awt.Font("HP Simplified Light", 0, 36)); // NOI18N
        jLabel16.setText("Roll no.          :");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(1340, 500, 210, 40);

        jLabel18.setFont(new java.awt.Font("HP Simplified Light", 0, 36)); // NOI18N
        jLabel18.setText("Date of birth :");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(1340, 560, 220, 40);

        jLabel25.setFont(new java.awt.Font("HP Simplified Light", 0, 36)); // NOI18N
        jLabel25.setText("Contact          :");
        jPanel1.add(jLabel25);
        jLabel25.setBounds(1340, 630, 250, 40);

        jLabel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel17);
        jLabel17.setBounds(1320, 130, 510, 590);

        jLabel26.setFont(new java.awt.Font("HP Simplified Light", 0, 36)); // NOI18N
        jLabel26.setText("2021");
        jPanel1.add(jLabel26);
        jLabel26.setBounds(1560, 360, 130, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tanay\\Desktop\\Final\\Background.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 0, 1920, 1080);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1920, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel21MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MousePressed
        Login l=new Login();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel21MousePressed

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
      MyResult r1 = new MyResult(UserID,loginAs,year,prn);
        r1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1MousePressed

public void getDetails()
   {
       try{  
                Class.forName("com.mysql.cj.jdbc.Driver");  
                Connection con=DriverManager.getConnection(  
                "jdbc:mysql://localhost:3306/college","root","TANay@99");
              PreparedStatement stmt=con.prepareStatement("call deletemessage()");  
                ResultSet rs=stmt.executeQuery(); 
                
                stmt=con.prepareStatement("SELECT * from noticeboard");  
                rs=stmt.executeQuery(); 
              
                
                String[] tblHead={"Posted by:","Date & time","Message"};
                DefaultTableModel dtm=new DefaultTableModel(tblHead,0);
                
                 while(rs.next()){
                  
                    String name = rs.getString(2);
                    String datestamp = rs.getString(3);
                    String message1 = rs.getString(4);
                  
                    message=name+"\t\t\t"+datestamp+"\t:\n\n"+message1+"\n------------------------------------------------------------------------------------------\n\n"+message; 
                }
                 textArea1.setText(message);
                                 
    
       }
       catch (Exception e)
       {
          JOptionPane.showMessageDialog(null,
                "error in loading noticeboard.");
       }}
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private java.awt.TextArea textArea1;
    // End of variables declaration//GEN-END:variables
}
