/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package college;

/**
 *
 * @author Tanay
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashboard");
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(null);

        jPanel1.setMaximumSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setMinimumSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("HP Simplified Light", 0, 36)); // NOI18N
        jLabel2.setText("Roll no. :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(1280, 410, 130, 50);

        jLabel3.setFont(new java.awt.Font("HP Simplified Light", 0, 36)); // NOI18N
        jLabel3.setText("Username :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(1280, 480, 190, 50);

        jLabel4.setFont(new java.awt.Font("HP Simplified Light", 0, 36)); // NOI18N
        jLabel4.setText("Admission ID :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(1960, -140, 210, 50);

        jLabel5.setFont(new java.awt.Font("HP Simplified Light", 0, 36)); // NOI18N
        jLabel5.setText("Year :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(1280, 260, 90, 40);

        jLabel6.setFont(new java.awt.Font("HP Simplified Light", 0, 36)); // NOI18N
        jLabel6.setText("Division :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(1280, 330, 140, 60);

        jLabel7.setFont(new java.awt.Font("HP Simplified Light", 0, 36)); // NOI18N
        jLabel7.setText("DOB :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(1280, 560, 80, 40);

        jLabel8.setFont(new java.awt.Font("HP Simplified Light", 0, 48)); // NOI18N
        jLabel8.setText("Hello,");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(170, 50, 120, 60);

        jLabel9.setFont(new java.awt.Font("HP Simplified Light", 0, 70)); // NOI18N
        jLabel9.setText("Tanay Dharmendra Patel");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(190, 90, 890, 100);

        jLabel10.setFont(new java.awt.Font("HP Simplified Light", 0, 36)); // NOI18N
        jLabel10.setText("Third year (TE.)");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(1380, 260, 230, 40);

        jLabel11.setFont(new java.awt.Font("HP Simplified Light", 0, 36)); // NOI18N
        jLabel11.setText("02");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(1420, 330, 100, 60);

        jLabel12.setFont(new java.awt.Font("HP Simplified Light", 0, 36)); // NOI18N
        jLabel12.setText("307165");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(1430, 410, 120, 50);

        jLabel13.setFont(new java.awt.Font("HP Simplified Light", 0, 36)); // NOI18N
        jLabel13.setText("1999-05-28");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(1380, 550, 200, 60);

        jLabel14.setFont(new java.awt.Font("HP Simplified Light", 0, 36)); // NOI18N
        jLabel14.setText("1234/ABCD");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(2180, -150, 230, 70);

        jLabel15.setFont(new java.awt.Font("HP Simplified Light", 0, 36)); // NOI18N
        jLabel15.setText("patel");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(1460, 480, 100, 50);

        jLabel16.setFont(new java.awt.Font("HP Simplified Light", 0, 36)); // NOI18N
        jLabel16.setText("Contact : 9403130058");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(1280, 630, 360, 40);

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("HP Simplified Light", 0, 36)); // NOI18N
        jButton1.setText("My Result");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(800, 400, 250, 60);

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("HP Simplified Light", 0, 36)); // NOI18N
        jButton2.setText("Attendance");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(500, 400, 250, 60);

        jLabel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel17);
        jLabel17.setBounds(1250, 160, 510, 550);

        jLabel18.setFont(new java.awt.Font("HP Simplified Light", 0, 36)); // NOI18N
        jLabel18.setText("Admission ID : ");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(1280, 190, 210, 50);

        jLabel19.setFont(new java.awt.Font("HP Simplified Light", 0, 36)); // NOI18N
        jLabel19.setText("abcd/1234/anbv");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(1500, 190, 270, 50);

        jLabel20.setFont(new java.awt.Font("HP Simplified Light", 0, 36)); // NOI18N
        jLabel20.setText("My details :");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(1250, 120, 170, 40);

        jLabel21.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tanay\\Downloads\\logout.png")); // NOI18N
        jLabel21.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel21);
        jLabel21.setBounds(30, 20, 60, 60);

        jLabel22.setText("Logout");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(50, 70, 48, 16);

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setFont(new java.awt.Font("HP Simplified Light", 0, 36)); // NOI18N
        jButton3.setText("Notice board");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(200, 400, 250, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tanay\\Desktop\\Final\\Background.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-10, 10, 1920, 1080);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1920, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
