/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package college;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author Tanay
 */
public class ForgotPassword1 extends javax.swing.JFrame {

    /**
     * Creates new form ForgotPassword1
     */
        private final ButtonGroup G;
    public String loginAs;
    public ForgotPassword1() {
        initComponents();
        G = new ButtonGroup();
        G.add(jRadioButton1);
        G.add(jRadioButton2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Forgot Password - 1");
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(null);

        jPanel1.setMaximumSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setMinimumSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("HP Simplified Light", 0, 50)); // NOI18N
        jLabel3.setText("Forgot Password");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(120, 20, 380, 70);

        jLabel9.setFont(new java.awt.Font("HP Simplified Light", 0, 24)); // NOI18N
        jLabel9.setText("User Validity");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(570, 40, 140, 40);

        jLabel20.setFont(new java.awt.Font("HP Simplified Light", 0, 24)); // NOI18N
        jLabel20.setText("Set new password");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(760, 40, 190, 40);

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 25)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 153, 0));
        jLabel11.setText("--------------");
        jLabel11.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel11);
        jLabel11.setBounds(560, 60, 170, 70);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Backward Arrow.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 30, 60, 60);

        jRadioButton2.setFont(new java.awt.Font("HP Simplified Light", 0, 36)); // NOI18N
        jRadioButton2.setText("Student");
        jRadioButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(530, 180, 150, 50);

        jRadioButton1.setFont(new java.awt.Font("HP Simplified Light", 0, 36)); // NOI18N
        jRadioButton1.setText("Teacher");
        jRadioButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(710, 180, 150, 50);

        jLabel4.setFont(new java.awt.Font("HP Simplified Light", 0, 24)); // NOI18N
        jLabel4.setText("You are  :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(400, 190, 100, 30);

        jLabel5.setFont(new java.awt.Font("HP Simplified Light", 0, 27)); // NOI18N
        jLabel5.setText("Registered username");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(440, 250, 240, 50);

        jLabel6.setFont(new java.awt.Font("HP Simplified Light", 0, 27)); // NOI18N
        jLabel6.setText("Q3.  What  is  your  favourite  food  dish  ?");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(400, 680, 540, 40);

        jLabel7.setFont(new java.awt.Font("HP Simplified Light", 0, 27)); // NOI18N
        jLabel7.setText("Q1.  In  which  city  you  were  born  ?");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(400, 430, 540, 40);

        jLabel8.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel8.setText(" *I want to reset my password");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(550, 950, 240, 30);

        jLabel10.setFont(new java.awt.Font("HP Simplified Light", 0, 27)); // NOI18N
        jLabel10.setText("Q2.  What  is  your  birth  month ?");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(400, 560, 380, 40);

        jTextField1.setBackground(new java.awt.Color(221, 221, 221));
        jTextField1.setFont(new java.awt.Font("HP Simplified Light", 0, 22)); // NOI18N
        jTextField1.setBorder(null);
        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(450, 480, 380, 50);

        jTextField2.setBackground(new java.awt.Color(221, 221, 221));
        jTextField2.setFont(new java.awt.Font("HP Simplified Light", 0, 22)); // NOI18N
        jTextField2.setBorder(null);
        jTextField2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2);
        jTextField2.setBounds(450, 610, 380, 50);

        jTextField3.setBackground(new java.awt.Color(221, 221, 221));
        jTextField3.setFont(new java.awt.Font("HP Simplified Light", 0, 22)); // NOI18N
        jTextField3.setBorder(null);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField3);
        jTextField3.setBounds(440, 300, 380, 50);

        jTextField4.setBackground(new java.awt.Color(221, 221, 221));
        jTextField4.setFont(new java.awt.Font("HP Simplified Light", 0, 22)); // NOI18N
        jTextField4.setBorder(null);
        jTextField4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField4);
        jTextField4.setBounds(450, 730, 380, 50);

        jButton1.setBackground(new java.awt.Color(221, 221, 221));
        jButton1.setFont(new java.awt.Font("HP Simplified Light", 0, 24)); // NOI18N
        jButton1.setText("Confirm & Proceed");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(520, 910, 240, 50);

        jLabel12.setFont(new java.awt.Font("HP Simplified Light", 1, 18)); // NOI18N
        jLabel12.setText("Security questions : ");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(400, 390, 170, 30);

        jLabel13.setFont(new java.awt.Font("HP Simplified Light", 3, 14)); // NOI18N
        jLabel13.setText("* All fields are compulsary");
        jLabel13.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel13);
        jLabel13.setBounds(710, 810, 230, 30);

        jLabel14.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel14.setText("Note : This action cannot be revoked.");
        jLabel14.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel14);
        jLabel14.setBounds(520, 870, 240, 30);

        jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel16.setName("dd"); // NOI18N
        jPanel1.add(jLabel16);
        jLabel16.setBounds(380, 240, 500, 570);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Login.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(1920, 1080));
        jLabel1.setMinimumSize(new java.awt.Dimension(1920, 1080));
        jLabel1.setName(""); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1920, 1080);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1920, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        Login l = new Login();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MousePressed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        if(jRadioButton2.isSelected()==true)
        {
            loginAs= " loginstudent ";
        }// TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        if(jRadioButton1.isSelected()==true)
        {
            loginAs= " loginteacher ";
        }// TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      String UserID= jTextField3.getText();  // TODO add your handling code here:
      String Secure1= jTextField1.getText();
      String Secure2= jTextField2.getText();
      String Secure3= jTextField4.getText();
      
      try
     {  
        //setup connection with database
        Class.forName("com.mysql.cj.jdbc.Driver");  
        Connection con=DriverManager.getConnection(  
        "jdbc:mysql://localhost:3306/college","Student","Student@99"); 
        
        boolean alreadyExists= false;
        
         PreparedStatement stmt=con.prepareStatement
        ("select * from "+loginAs+" where UserID = ?");
         stmt.setString(1, UserID);
     
         
         ResultSet rs=stmt.executeQuery(); 
         
         while(rs.next())
         {
             
             alreadyExists= true;
            
           if (Secure1.equals(rs.getString(4)))
             {
                 if (Secure2.equals(rs.getString(5)))
                 {
                     if (Secure3.equals(rs.getString(6)))
                     {
                          this.dispose();
                          ResetPassword RP = new ResetPassword(UserID,loginAs);
                          RP.setVisible(true);
                     }
                     else
                     {
                         JOptionPane.showMessageDialog(null,"Third security answer does not match.");
                     }
                 }
                 else
                 {
                     JOptionPane.showMessageDialog(null,"Second security answer does not match."); 
                 }
         
             }
             else
             {
                 JOptionPane.showMessageDialog(null,"First security answer does not match."); 
             }
         
         }
         if(alreadyExists==false)
         {
             JOptionPane.showMessageDialog(null,"Entered username doesn not exists.\nPlease enter correct details."); 
         }
         
   
        
     }
           catch(Exception e) 
     {
         JOptionPane.showMessageDialog(null,
         "Please fill details completly and correctly."); 
     }
      
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgotPassword1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
