/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package college;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Tanay
 */
public class ResetPassword extends javax.swing.JFrame {

    /**
     * Creates new form ResetPassword
     */
    String UserID,loginAs;
   
    public ResetPassword(String _UserID,String _loginAs) {
        this.UserID = _UserID;
        this.loginAs=_loginAs;
        initComponents();
        String Account;
        if(loginAs.equals(" loginstudent "))
        {
            Account="Student";
        }
        else
        {
            Account="Teacher";
        }
      
        try
        {
             //setup connection with database
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/college","Student","Student@99");
            
            PreparedStatement stmt=con.prepareStatement
            ("select FirstName,MiddleName,LastName from "+Account+" where UserID = ?");
            stmt.setString(1, UserID);
           
            ResultSet rs=stmt.executeQuery();
            while(rs.next())
            {
              
            jLabel6.setText(rs.getString(1)+"  "+rs.getString(2)+"  "+rs.getString(3));
            }
                      
        }
         catch (Exception e)
        {
            JOptionPane.showMessageDialog(null,
                "Unable to connect to database.");
        }// TODO add your handling code here:
    }

    private ResetPassword() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel16 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reset Password");
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(null);

        jPanel1.setMaximumSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setMinimumSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("HP Simplified Light", 0, 50)); // NOI18N
        jLabel3.setText("Reset Password");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(120, 20, 380, 70);

        jLabel9.setFont(new java.awt.Font("HP Simplified Light", 0, 24)); // NOI18N
        jLabel9.setText("User Validity");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(570, 40, 140, 40);

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 25)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 153, 0));
        jLabel11.setText("------------------");
        jLabel11.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel11);
        jLabel11.setBounds(760, 60, 220, 70);

        jLabel20.setFont(new java.awt.Font("HP Simplified Light", 0, 24)); // NOI18N
        jLabel20.setText("Set new password");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(760, 40, 190, 40);

        jLabel5.setFont(new java.awt.Font("HP Simplified Light", 0, 36)); // NOI18N
        jLabel5.setText("Enter new password");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(430, 300, 310, 50);

        jLabel2.setFont(new java.awt.Font("HP Simplified Light", 0, 28)); // NOI18N
        jLabel2.setText("Please create a new password for your account");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(360, 230, 600, 70);

        jButton1.setFont(new java.awt.Font("HP Simplified Light", 0, 24)); // NOI18N
        jButton1.setText("Reset Password");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(510, 720, 200, 60);

        jLabel4.setFont(new java.awt.Font("HP Simplified Light", 0, 36)); // NOI18N
        jLabel4.setText("Hello, ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(360, 150, 100, 70);

        jLabel6.setFont(new java.awt.Font("HP Simplified Light", 0, 50)); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(460, 150, 560, 60);

        jLabel7.setFont(new java.awt.Font("HP Simplified Light", 0, 36)); // NOI18N
        jLabel7.setText("Confirm password");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(430, 460, 350, 50);

        jPasswordField1.setBackground(new java.awt.Color(221, 221, 221));
        jPasswordField1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jPasswordField1.setBorder(null);
        jPasswordField1.setPreferredSize(new java.awt.Dimension(370, 50));
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jPasswordField1);
        jPasswordField1.setBounds(440, 530, 370, 50);

        jPasswordField2.setBackground(new java.awt.Color(221, 221, 221));
        jPasswordField2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jPasswordField2.setBorder(null);
        jPasswordField2.setPreferredSize(new java.awt.Dimension(370, 50));
        jPasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jPasswordField2);
        jPasswordField2.setBounds(440, 360, 370, 50);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel16.setName("dd"); // NOI18N
        jPanel1.add(jLabel16);
        jLabel16.setBounds(370, 290, 500, 350);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Login.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(1920, 1080));
        jLabel1.setMinimumSize(new java.awt.Dimension(1920, 1080));
        jLabel1.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jLabel1.setRequestFocusEnabled(false);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1920, 1080);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1920, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        try
        {
             //setup connection with database
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/college","root","TANay@99");  
            
            String Password1 = String.valueOf(jPasswordField2.getPassword());
            String Password2 = String.valueOf(jPasswordField1.getPassword());
            if(Password1.equals(Password2))
            {
            String query = "update " + loginAs + " set Password=? where UserID=?";
            PreparedStatement preparedStmt = con.prepareStatement(query);
            preparedStmt.setString(1, Password1);
            preparedStmt.setString(2, UserID);
            preparedStmt.executeUpdate();
            
            JOptionPane.showMessageDialog(null,
                "Password updates successfuly !\nPlease try to login with your new password.");
            
            Login l=new Login();
            l.setVisible(true);
            this.dispose();
            }
            else
            {
                JOptionPane.showMessageDialog(null,
                "Password does not match.\nPlease enter password again.");
            }
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null,
                "Error Occured.");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResetPassword().setVisible(true);
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    // End of variables declaration//GEN-END:variables
}
