/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package college;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tanay
 */
public class ReviewApplication extends javax.swing.JFrame {

    /**
     * Creates new form ReviewApplication
     */
    private final ButtonGroup G;
    String UserID,loginAs,account=" ",table,year;
    int roll;
    public ReviewApplication(String _UserID,String _loginAs) {
        this.UserID = _UserID;
        this.loginAs=_loginAs;
        initComponents(); 
        G = new ButtonGroup();
        G.add(jRadioButton1);
        G.add(jRadioButton2);
        this.getDetails();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setMaximumSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setMinimumSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setLayout(null);

        jButton1.setBackground(new java.awt.Color(218, 224, 228));
        jButton1.setFont(new java.awt.Font("Arial Narrow", 0, 32)); // NOI18N
        jButton1.setText("Reject");
        jButton1.setBorder(null);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(1740, 530, 120, 60);

        jLabel2.setFont(new java.awt.Font("HP Simplified Light", 0, 32)); // NOI18N
        jLabel2.setText("Username :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(1540, 430, 190, 48);

        jRadioButton1.setBackground(new java.awt.Color(213, 223, 228));
        jRadioButton1.setFont(new java.awt.Font("HP Simplified Light", 0, 32)); // NOI18N
        jRadioButton1.setText("Student");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(1550, 320, 150, 50);

        jRadioButton2.setBackground(new java.awt.Color(218, 226, 230));
        jRadioButton2.setFont(new java.awt.Font("HP Simplified Light", 0, 32)); // NOI18N
        jRadioButton2.setText("Teacher");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(1720, 320, 150, 50);

        jLabel3.setFont(new java.awt.Font("HP Simplified Light", 0, 32)); // NOI18N
        jLabel3.setText("Activate account of :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(1530, 250, 300, 40);

        jTextField1.setBackground(new java.awt.Color(214, 219, 222));
        jTextField1.setFont(new java.awt.Font("HP Simplified Light", 0, 30)); // NOI18N
        jTextField1.setBorder(null);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(1700, 430, 180, 50);

        jLabel5.setFont(new java.awt.Font("HP Simplified Light", 0, 55)); // NOI18N
        jLabel5.setText("Activate account");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(130, 30, 420, 70);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Backward Arrow.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel6MousePressed(evt);
            }
        });
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 30, 70, 60);

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "User ID", "Admissin ID", "First Name", "Last Name", "Middle Name", "Year", "Division", "Contact", "Gender", "DOB"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setEnabled(false);
        jTable1.setOpaque(false);
        jTable1.setRequestFocusEnabled(false);
        jTable1.setRowHeight(40);
        jTable1.setRowMargin(4);
        jTable1.setSelectionBackground(new java.awt.Color(204, 204, 204));
        jTable1.setSelectionForeground(new java.awt.Color(51, 51, 51));
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(1).setMinWidth(25);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(25);
            jTable1.getColumnModel().getColumn(1).setMaxWidth(25);
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(110, 500, 1340, 150);

        jButton2.setBackground(new java.awt.Color(218, 224, 228));
        jButton2.setFont(new java.awt.Font("Arial Narrow", 0, 32)); // NOI18N
        jButton2.setText("Approve");
        jButton2.setBorder(null);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(1560, 530, 130, 60);

        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel4);
        jLabel4.setBounds(1520, 240, 370, 380);

        jTable2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "User ID", "Admissin ID", "First Name", "Last Name", "Middle Name", "Year", "Division", "Contact", "Gender", "DOB"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setEnabled(false);
        jTable2.setOpaque(false);
        jTable2.setRequestFocusEnabled(false);
        jTable2.setRowHeight(40);
        jTable2.setRowMargin(4);
        jTable2.setSelectionBackground(new java.awt.Color(204, 204, 204));
        jTable2.setSelectionForeground(new java.awt.Color(51, 51, 51));
        jTable2.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(1).setMinWidth(25);
            jTable2.getColumnModel().getColumn(1).setPreferredWidth(25);
            jTable2.getColumnModel().getColumn(1).setMaxWidth(25);
        }

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(100, 180, 1350, 200);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("Teacher's account :-");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(110, 460, 230, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("Student's accounts :-");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(100, 140, 230, 40);

        jLabel1.setBackground(new java.awt.Color(218, 224, 228));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tanay\\Desktop\\Final\\Background.jpg")); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1920, 1080);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1920, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
       if(jRadioButton1.isSelected()==true)
        {
            account= "loginstudent";
           
        } // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jLabel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MousePressed
        DashboardHod DH= new DashboardHod(UserID,loginAs);
                DH.setVisible(true);
                this.dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MousePressed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        if(jRadioButton2.isSelected()==true)
        {
            account= "loginteacher";
           
        }// TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
       String Username= jTextField1.getText();
       boolean GoAhead=true;
      if(Username.equals("") || account.equals(" "))
      {JOptionPane.showMessageDialog(null,"Please enter deatails completly\nUsername and type of applicant"); GoAhead=false;}
      else{
          
          if (account.equals("loginteacher"))
        {table="teacher";}
       else if (account.equals("loginstudent"))
        {table="student";}
       
       try{
           //setup connection with database
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/college", "root", "TANay@99");
            
            PreparedStatement preparedStmt = con.prepareStatement("delete from "+table+" where userid=(select userid from "+account+" where status=0 and userid=?)");
            preparedStmt.setString(1,Username);
            int rowAffected = preparedStmt.executeUpdate();
         
            preparedStmt = con.prepareStatement("delete from "+account+" where userid=? and status=0");
            preparedStmt.setString(1,Username);
            rowAffected = preparedStmt.executeUpdate();
            getDetails();
            
            JOptionPane.showMessageDialog(null, "Application rejected.");
            jTextField1.setText("");
       }    
       catch(Exception e)
       {JOptionPane.showMessageDialog(null,"Connection to database not succeded");}
      }
       
    }//GEN-LAST:event_jButton1MousePressed

    private void jButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MousePressed
        String Username= jTextField1.getText();
        
        boolean GoAhead=true;
        if(Username.equals("") || account.equals(" "))
        {JOptionPane.showMessageDialog(null,"Please enter deatails completly\nUsername and type of applicant"); GoAhead=false;}
        else{
            if (account.equals("loginteacher"))
            {table="teacher";
            
            try{
           //setup connection with database
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/college", "root", "TANay@99");
            
            PreparedStatement stmt=con.prepareStatement("select max(teacherid) from "+table);
            ResultSet rs=stmt.executeQuery(); 
            while (rs.next())
            {
                   roll=rs.getInt(1);
            }
            roll=roll+1;
            stmt=con.prepareStatement("update "+table+" set teacherid="+roll+" where userid=?");
            stmt.setString(1,Username);
            int rowAffected = stmt.executeUpdate();
            stmt=con.prepareStatement("update "+account+" set status=1 where userid=?");
            stmt.setString(1,Username);
            rowAffected = stmt.executeUpdate();
            getDetails();
            
            }
            
            catch(Exception e){JOptionPane.showMessageDialog(null,"Connection to database not succeded");}
            }
            
            else if (account.equals("loginstudent"))
            {table="student";
       
            try{
           //setup connection with database
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/college", "root", "TANay@99");
            
            PreparedStatement stmt=con.prepareStatement("select year from "+table+" where userid=?");
            stmt.setString(1, Username);
            ResultSet rs=stmt.executeQuery(); 
            while (rs.next())
            {
                   year=rs.getString(1);
            }
            
            stmt=con.prepareStatement("select max(rollno) from "+table+" where year=?");
            stmt.setString(1,year);
            rs=stmt.executeQuery(); 
            while (rs.next())
            {
                    roll=rs.getInt(1);
            }
            
            roll=roll+1;
            stmt=con.prepareStatement("update "+table+" set rollno="+roll+" where userid=?");
            stmt.setString(1,Username);
            int rowAffected = stmt.executeUpdate();
            stmt=con.prepareStatement("update "+account+" set status=1 where userid=?");
            stmt.setString(1,Username);
            rowAffected = stmt.executeUpdate();
            getDetails();
            JOptionPane.showMessageDialog(null, "Account approved.");
            jTextField1.setText("");
        }
            catch(Exception e){JOptionPane.showMessageDialog(null,"Connection to database not succeded");}
        }
        }
       
    }//GEN-LAST:event_jButton2MousePressed

    /**
     * @param args the command line arguments
     */
   public void getDetails()
   {
       try{  
                Class.forName("com.mysql.cj.jdbc.Driver");  
                Connection con=DriverManager.getConnection(  
                "jdbc:mysql://localhost:3306/college","root","TANay@99");
                
                PreparedStatement stmt=con.prepareStatement(" select  a.UserID,b.PRN,b.FirstName,b.LastName,b.MiddleName,b.Year, b.Division,b.Contact,b.Gender,b.DOB from loginstudent a left join student b on a.userid=b.userid where a.status= 0;");  
                ResultSet rs=stmt.executeQuery(); 
                
                String[] tblHead={"Uesr ID","PRN","First Name","Last Name","Middle Name","Year","Division","Contact","Gender","DOB"};
                DefaultTableModel dtm=new DefaultTableModel(tblHead,0);
                
                 while(rs.next()){
                    //count ++;
                    String UserID = rs.getString(1);
                    String PRN = rs.getString(2);
                    String FirstName = rs.getString(3);
                    String LastName = rs.getString(4);
                    String MiddleName = rs.getString(5);
                    String Year = rs.getString(6);
                    String Division = rs.getString(7);
                    String Contact  = rs.getString(8);
                    String Gender  = rs.getString(9);
                    String DOB  = rs.getString(10);
                    String[] item={UserID,PRN,FirstName,LastName, MiddleName,Year, Division,Contact,Gender,DOB};
                    dtm.addRow(item);
                 //   System.out.println(UserID+" "+AdmissionID+" "+FirstName+" "+LastName+" "+MiddleName+" "+Year+" "+Division+" "+Contact+" "+Gender+" "+DOB);  
                }
                 
                  
                  
                  //Pending Teacher
                PreparedStatement stmt2=con.prepareStatement("SELECT  a.UserID,b.FirstName,b.LastName,b.MiddleName,b.Experience, b.Designation,b.Contact,b.Qualification,b.DOB,b.MaritalStatus,b.gender FROM  loginteacher a LEFT JOIN teacher b on a.userid=b.userid where a.status=0");  
                ResultSet rs2=stmt2.executeQuery(); 
                
                String[] tblHead2={"Uesr ID","First Name","Last Name","Middle Name","Qualification","Experience","Designation","Marital Status","DOB","Contact","Gender"};
                DefaultTableModel dtm2=new DefaultTableModel(tblHead2,0);
                
                 while(rs2.next()){
                    //count ++;
                    String UserID = rs2.getString(1);
                    String FirstName = rs2.getString(2);
                    String LastName = rs2.getString(3);
                    String MiddleName = rs2.getString(4);
                    
                    String Experience = rs2.getString(5);
                    String Designation  = rs2.getString(6);
                    String Contact  = rs2.getString(7);
                    String Qualification = rs2.getString(8);
                    String DOB  = rs2.getString(9);
                    String MaritalStatus  = rs2.getString(10);
                    
                    
                    String Gender = rs2.getString(11);
                    String[] item={UserID,FirstName,LastName, MiddleName,Qualification,Experience,Designation,MaritalStatus,DOB,Contact,Gender};
                    dtm2.addRow(item);
                    System.out.println(UserID+" "+FirstName+" "+LastName+" "+MiddleName+" "+Qualification+" "+Experience+" "+Designation+" "+MaritalStatus+" "+DOB+" "+Contact+" "+Gender);  
                }
                  jTable2.setModel(dtm);
                  jTable1.setModel(dtm2);
       }
       catch (Exception e)
       {
           JOptionPane.showMessageDialog(null, "Currently no applications to review");
       }
  
   }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
