/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package college;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Calendar;
import java.util.TimeZone;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tanay
 */
public class StudentsDetail2 extends javax.swing.JFrame {

    /**
     * Creates new form StudentsDetail2
     */
    String UserID,loginAs,search,PRN,year,year2;
    public StudentsDetail2(String _UserID,String _loginAs) {
        this.UserID = _UserID;
        this.loginAs=_loginAs;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student details");
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(null);

        jPanel1.setMaximumSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setMinimumSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Backward Arrow.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 20, 70, 60);

        jLabel3.setFont(new java.awt.Font("HP Simplified Light", 0, 48)); // NOI18N
        jLabel3.setText("Student details");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(150, 20, 330, 70);

        jTable1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setRowHeight(24);
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(620, 150, 1250, 610);

        jComboBox1.setBackground(new java.awt.Color(221, 221, 221));
        jComboBox1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--select--", "First year (FE)", "Second year (SE)", "Third year (TE)", "Fourth year (BE)" }));
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jComboBox1MousePressed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(120, 270, 310, 50);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel6.setText("Batch:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(120, 470, 280, 50);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel5.setText("Search by PRN :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(120, 350, 230, 50);

        jTextField1.setBackground(new java.awt.Color(221, 221, 221));
        jTextField1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jTextField1.setBorder(null);
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(120, 520, 310, 50);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel7.setText("Current Study year:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(120, 220, 280, 50);

        jTextField2.setBackground(new java.awt.Color(221, 221, 221));
        jTextField2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jTextField2.setBorder(null);
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField2);
        jTextField2.setBounds(120, 400, 310, 50);

        jButton1.setFont(new java.awt.Font("Times New Roman", 2, 36)); // NOI18N
        jButton1.setText("Search");
        jButton1.setBorder(null);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(200, 610, 170, 60);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Filter search");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel4.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, null));
        jPanel1.add(jLabel4);
        jLabel4.setBounds(80, 150, 400, 540);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Background.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1920, 1080);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1920, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
       if (UserID.equals("hod") )      
            {
                DashboardHod DH= new DashboardHod(UserID,loginAs);
                DH.setVisible(true);
                this.dispose(); 
            }
            else
            {
                DashboardTeacher DT= new DashboardTeacher(UserID,loginAs);
                DT.setVisible(true);
                this.dispose(); 
            }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
       int key=evt.getKeyCode();
       jComboBox1.setSelectedItem("--select--");
       jTextField2.setText("");        
        if((key>=evt.VK_0&&key<=evt.VK_9)||(key>=evt.VK_NUMPAD0&&key<=evt.VK_NUMPAD9)||key==evt.VK_BACK_SPACE)
        {
           boolean set=true;
        }
        else
        {
            jTextField1.setText("");
            JOptionPane.showMessageDialog(null, "Only digits are allowed");
        }           
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed
        jTextField1.setText("");
        jComboBox1.setSelectedItem("--select--");
    }//GEN-LAST:event_jTextField2KeyPressed

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
     PRN=jTextField2.getText();
     year=jTextField1.getText();
     year2 = jComboBox1.getSelectedItem().toString();
     
       if(year2.equals("--select--")&&PRN.equals("")&&year.equals(""))
       {JOptionPane.showMessageDialog(null, "Invalid filter selected");}
     
       else
       {
           if(PRN.equals("")&&year.equals(""))
           {search= " where year='"+year2+"'";//combobox
           }
           
           else if(PRN.equals("")&&year2.equals("--select--"))//batch year
           {search="where batch="+year;}
           else if(year.equals("")&&year2.equals("--select--"))//PRN
           {search="where prn='"+PRN+"'";}
       
           try{
    
       Class.forName("com.mysql.cj.jdbc.Driver");  
       Connection con=DriverManager.getConnection(  
       "jdbc:mysql://localhost:3306/college","root","TANay@99");
       
       PreparedStatement stmt=con.prepareStatement("select * from student "+search);
       ResultSet rs=stmt.executeQuery(); 
       
       String[]   tblHead={"UserID","PRN","Rollno","FirstName","LastName","MiddleName","Year","Batch","Division","Contact","Gender","DOB"};
            DefaultTableModel dtm1=new DefaultTableModel(tblHead,0);
          
            while (rs.next())
            {
                    String user = rs.getString(1);
                    String prn = rs.getString(2);
                    String Roll = rs.getString(3);
                    String FirstName = rs.getString(4);
                    String LastName = rs.getString(5);
                    String MiddleName= rs.getString(6);
                    String Year = rs.getString(7);
                    String Batch = rs.getString(8);
                    String Division = rs.getString(9);
                    String Contact= rs.getString(10);
                    String Gender = rs.getString(11);
                    String DOB = rs.getString(12);
                   
                    String[] item={user,prn,Roll,FirstName,LastName,MiddleName,Year,Batch,Division,Contact,Gender,DOB};
                    dtm1.addRow(item);
                    System.out.println(user+" "+prn+" "+Roll+" "+FirstName+" "+LastName+" "+MiddleName+" "+Year+" "+Batch+" "+Division+" "+Contact+" "+Gender+" "+DOB);
                }
                jTable1.setModel(dtm1);
           }
           catch(Exception e){JOptionPane.showMessageDialog(null,"Failed");
       }
       }
    }//GEN-LAST:event_jButton1MousePressed

    private void jComboBox1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MousePressed
          jTextField1.setText("");
        jTextField2.setText("");   
    }//GEN-LAST:event_jComboBox1MousePressed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
