/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package college;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tanay
 */
public class TeacherDetails extends javax.swing.JFrame {

    /**
     * Creates new form TeacherDetails
     */ String UserID,loginAs,search,PRN,year,year2;
    public TeacherDetails(String _UserID,String _loginAs) {
        this.UserID = _UserID;
        this.loginAs=_loginAs;
        initComponents();
        getdetails();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(null);

        jPanel1.setMaximumSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setMinimumSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("HP Simplified Light", 0, 48)); // NOI18N
        jLabel3.setText("Teachers detail");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(150, 20, 330, 70);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Backward Arrow.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 20, 70, 60);

        jTable1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setRowHeight(30);
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(240, 180, 1250, 570);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Background.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1920, 1080);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1920, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
            DashboardHod DH= new DashboardHod(UserID,loginAs);
            DH.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    public void getdetails()
    {
    try{
    
       Class.forName("com.mysql.cj.jdbc.Driver");  
       Connection con=DriverManager.getConnection(  
       "jdbc:mysql://localhost:3306/college","root","TANay@99");
       
       PreparedStatement stmt=con.prepareStatement("select * from teacher");
       ResultSet rs=stmt.executeQuery(); 
       
       String[]   tblHead={"UserID","TeacherID","FirstName","LastName","MiddleName","Designation","Experience","Qualification","Contact","Gender","DOB","MaritalStatus"};
            DefaultTableModel dtm1=new DefaultTableModel(tblHead,0);
          
            while (rs.next())
            {
                    String prn = rs.getString(1);
                    String Roll = rs.getString(2);
                    String FirstName = rs.getString(3);
                    String LastName = rs.getString(4);
                    String MiddleName= rs.getString(5);
                    String Designation = rs.getString(7);
                    String Experience = rs.getString(8);
                    String Qualification = rs.getString(9);
                    String Contact= rs.getString(6);
                    String Gender = rs.getString(11);
                    String DOB = rs.getString(10);
                    String MS=rs.getString(12);
                    String[] item={prn,Roll,FirstName,LastName,MiddleName,Designation,Experience,Qualification,Contact,Gender,DOB,MS};
                    dtm1.addRow(item);
                    System.out.println(prn+" "+Roll+" "+FirstName+" "+LastName+" "+MiddleName+" "+Designation+" "+Experience+" "+Qualification+" "+Contact+" "+Gender+" "+DOB+" "+MS);
                }
                jTable1.setModel(dtm1);
           }
           catch(Exception e){JOptionPane.showMessageDialog(null,"Failed");
       }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
